name: Automotive Lighting Solutions
favicon: null
layout_spectrum: 0.32576576876454055
typography_spectrum: 0.6275949932169169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6093411231413484
  lightness: 0.3785579036921263
  saturation: 0.5196666172705591
  rhythmicContrast: 0.45352129242382944
purpose: []
